finnished
arakaki0118/My_Work pull request #1
Opened 2022-12-02 23:20 UTC by arakaki0118

完成コード
菅田さんレビューをお願いいたします。

2022-12-03 01:30 UTC, kotasugya requested changes
レスポンシブ対応も施されており、非常に素晴らしいと思います。
特に問題点は見当たりませんでしたが、1カ所コメントしたので、ご確認ください。
また、`.DS_Store`というファイルが混ざっておりますが、不要であれば、削除してください。

2022-12-03 01:30 UTC, kotasugya commented on index.html
> +        <li><a href="#">About</a></li>
こちらの<a>タグが機能していないと思います。この記述ではクリックしても遷移しないはずです。

2022-12-03 22:54 UTC, arakaki0118 commented on index.html
> +        <li><a href="#">About</a></li>
リンクの記載設定抜けていました。
修正後再度プルリクエストさせていただきます。

2022-12-06 14:15 UTC, kotasugya commented
修正確認できました。
マージして問題ないと思います！

2022-12-06 23:52 UTC, merged